# Generated by Django 4.0.5 on 2022-07-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(max_length=4, verbose_name='ID convite')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('adult_guest', models.IntegerField(default=0, verbose_name='Adultos')),
                ('child_guest', models.IntegerField(default=0, verbose_name='Crianças')),
                ('whatsapp', models.CharField(max_length=15, verbose_name='Whatsapp')),
                ('invite_status', models.IntegerField(default=0, verbose_name='Estado do convite')),
            ],
        ),
    ]
